### ISSUE TITLE
Anomalous readings

### ISSUE THREAD

**Issue by fcooper8472** [jamtholee/flags#11]
Any idea what's been causing the few weird readings recently?

- Thursday, Dec 01, 11:00, reading way too high
- Friday, Nov 25, 14:15, reading something big and negative
- Tuesday, Nov 22, immediately after 21:30, reading something big and negative

The main issue is auto scaling on the y-axis doesn't play well with the extremely high reading from a few days ago.

**Comment by JoeHitchen** [comment]
The root cause of all of these will be spurious measurements from one of the measuring stations on the reach - We perform only basic arithmetic on these readings and we don't have any noise filtering in place.

I've deleted the latest high reading since it was affecting usability!

**Comment by fcooper8472** [comment]
If you wanted to consider adding any filtering I'd be happy to help, but closing this for now.
