### ISSUE TITLE
Grey Flag predictions

### ISSUE THREAD

**Issue by thomas-chapman** [jamtholee/flags#3]
![image](https://user-images.githubusercontent.com/58432429/74536405-e9099d00-4f2f-11ea-886f-9bbf7bd426d2.png)
What causes a grey prediction here?

**Comment by JoeHitchen** [comment]
Looks like an upstream outage of the prediction microservice. @jamtholee requests are timing out.

**Comment by jamtholee** [comment]
Thanks for letting me know - I'll have a look at it this evening when I get home

**Comment by JoeHitchen** [comment]
(Spoiler alert - The prediction will be red with 0.99 confidence)

**Comment by jamtholee** [comment]
Now back online
