### ISSUE TITLE
Not sure what "Prediction: Grey" means

### ISSUE THREAD

**Issue by fcooper8472** [jamtholee/flags#7]
I assume the Grey flag is obtained from the OURCs flag status API, and is not predicted by your model.

Could you predict the flag colour just based on your model, and display the actual flag colour as a separate data field?

**Comment by jamtholee** [comment]
Cheers for the heads up - the ML prediction service runs on a separate server which sometimes falls over which I don't notice or catch.  Have fixed now and rebooted.

A "grey" result in the top right box normally means that server is down.

**Comment by fcooper8472** [comment]
Thanks!
